### ISSUE TITLE
[FE] [Calendar] calendar corrupted when when it gets "Failed prop type: The prop `event.host.status`" error.

### ISSUE THREAD

**Issue by drozdovkostya** [ratifire/devrate-web#774]
Steps to reproduce:
Open Chrome in private mode
Refresh the page several times.

![Image](https://github.com/user-attachments/assets/252a8818-8f7d-4470-9065-58fd43ed0b7f)

> Warning: Failed prop type: The prop `event.host.status` is marked as required in `SidebarEvent`, but its value is `null`.
    at SidebarEvent (https://devrate.org/static/js/bundle.js:28687:3)
    at Sidebar (https://devrate.org/static/js/bundle.js:28010:3)
    at div
    at https://devrate.org/static/js/bundle.js:42895:66
    at Box (https://devrate.org/static/js/bundle.js:78259:72)
    at Schedule (https://devrate.org/static/js/bundle.js:27524:68)
    at div
    at https://devrate.org/static/js/bundle.js:42895:66
    at Paper (https://devrate.org/static/js/bundle.js:64754:83)
    at div
    at https://devrate.org/static/js/bundle.js:42895:66
    at Paper (https://devrate.org/static/js/bundle.js:64754:83)
    at div
    at https://devrate.org/static/js/bundle.js:42895:66
    at Box (https://devrate.org/static/js/bundle.js:78259:72)
    at div
    at https://devrate.org/static/js/bundle.js:42895:66
    at Container (https://devrate.org/static/js/bundle.js:77068:19)
    at div
    at ScheduleTemplate (https://devrate.org/static/js/bundle.js:3790:3)
    at SchedulePage (https://devrate.org/static/js/bundle.js:34244:68)
    at RenderedRoute (https://devrate.org/static/js/bundle.js:137660:5)
    at Outlet (https://devrate.org/static/js/bundle.js:138264:26)
    at RequireAuth (https://devrate.org/static/js/bundle.js:35081:79)
    at RenderedRoute (https://devrate.org/static/js/bundle.js:137660:5)
    at Outlet (https://devrate.org/static/js/bundle.js:138264:26)
    at ToastLayout
    at RenderedRoute (https://devrate.org/static/js/bundle.js:137660:5)
    at RenderErrorBoundary (https://devrate.org/static/js/bundle.js:137607:5)
    at DataRoutes (https://devrate.org/static/js/bundle.js:136246:5)
    at Router (https://devrate.org/static/js/bundle.js:138285:15)
    at RouterProvider (https://devrate.org/static/js/bundle.js:136033:5)
    at App
    at RtlProvider (https://devrate.org/static/js/bundle.js:77200:7)
    at ThemeProvider (https://devrate.org/static/js/bundle.js:76008:5)
    at ThemeProvider (https://devrate.org/static/js/bundle.js:77489:5)
    at ThemeProvider (https://devrate.org/static/js/bundle.js:74411:14)
    at ThemedApp (https://devrate.org/static/js/bundle.js:32506:77)
    at PersistGate (https://devrate.org/static/js/bundle.js:145683:5)
    at Provider (https://devrate.org/static/js/bundle.js:196561:3)
    at Suspense

**Comment by vplabunets** [comment]
Hi. Could you please, retest current bug. Seems, that it was solved.
